baseURL = "https://yfhuang7.github.io/"
languageCode = "en-us"
title = "Yu-Fen Huang"
theme = "minimal"
disqusShortname = "yfhuang7" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Yu-Fen Huang"
    description = "Hydrologist | Data Scientist | Body Surfer | Hula Lover | Foodie | Ph.D. student in TsangStreamLab | Natural Resources and Environmental Management | University of Hawaiʻi at Mānoa"
    githubUsername = "yfhuang7"
    accent = "#4F97A3"
    showBorder = true
    backgroundColor = "white"
    font = "Vollkorn" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "R", "bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://yufenhuang.notion.site/YU-FEN-HUANG-9152a5c75bc8467289ae6896a45b317f?pvs=4"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3
[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 4

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:yfhuang@hawaii.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/yfhuang7/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/WaterYFHuang/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/yu-fen-（郁芬）-huang-（黃）-b3571267/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCtcPhvfrkjNhRcSFRBuIkvg"
    name = "youtube"
    weight = 5

#[[menu.icon]]
#    url = "https://www.instagram.com/yufenasyourfriend/"
#    name = "instagram"
#    weight = 6
